### ISSUE TITLE
refactore the import system. change to local paths

### ISSUE THREAD

**Issue by utnapischtim** [fair-data-austria/invenio-rdm-pure#18]
it was necessary to change the import system from not really local path to absolute paths to have a running test installation with the #17 PR.

This should be reverted in the sense the a local python module should be included with a dot in front. This shows clearly that the import is coming from the current python package.

this is also done in other invenio modules like [1]

[1] https://github.com/inveniosoftware/invenio-rdm-records/blob/9401a3436bc17a00ba7a1989a752791101ce861d/invenio_rdm_records/cli.py#L26

**Comment by bengaal** [comment]
This issue should be resolved in 1cd7c67b8136d1d11b95ce1a1a5fe13c5a05eb05, 36bfec99326d86a35cbdab9d631a4a462b0cc3be and 703671a01f658b199f9c581cc9c9a270f3732526.
