### ISSUE TITLE
BUG: find out what is about the cannot parse file error in

### ISSUE THREAD

**Issue by utnapischtim** [fair-data-austria/invenio-rdm-pure#19]
the PR #17 brought up some parsing problems. This should be fixed. It is the commented code starting from the following references:

https://github.com/tu-graz-library/invenio-rdm-pure/blob/8096ede13da03d992987c05e81a7b351c665f5e1/invenio_rdm_pure/source/pure/import_records.py#L284

https://github.com/tu-graz-library/invenio-rdm-pure/blob/8096ede13da03d992987c05e81a7b351c665f5e1/invenio_rdm_pure/source/rdm/add_record.py#L376

https://github.com/tu-graz-library/invenio-rdm-pure/blob/8096ede13da03d992987c05e81a7b351c665f5e1/invenio_rdm_pure/source/rdm/run/groups.py#L242

**Comment by bengaal** [comment]
Issue resolved in a7a501eb3a53229573bc1d42f2437ae8da624e41.
