### ISSUE TITLE
refactore the installation process

### ISSUE THREAD

**Issue by utnapischtim** [fair-data-austria/invenio-rdm-pure#5]
# Current installation process:
* Before installing the module, 
a. one must run ```python ../invenio-rdm-pure/invenio_rdm_pure/initial_setup.py```. in order to add some values for needed configurations: such as ```pure_username```, ```pure_api_key``` and so on... [1].
These values and variables then are saved to ```invenio_rdm_records/data_setup```.
b. creates a default user based on the giving values.

# Expected refactor
The installation process should put the module in a workable state.
- [x] move all these configuration variables from ```initial_setup.py```, to config variable of ```config.py```. that we the user can define these variables and their values also outside of the module.
- [x] ```./run-tests.sh``` should pass without errors in the module.
- [x] Create owner user for imported records with administrator rights at the installation process or at the first execution.
- [ ] @utnapischtim Add here what else .. there is to installing the module.

[1] https://github.com/tu-graz-library/invenio-rdm-pure/blob/0888fa020f233c6b9abbf3e14b51c746fd12a4e6/invenio_rdm_pure/initial_setup.py#L16

**Comment by bengaal** [comment]
9298cb168c2d456594b296a6a1bf3fd658bb10aa should resolve TODO #3.

**Comment by bengaal** [comment]
3c8e6293d965cb1b7385d62e44899111434e7df9 Removes `initial_setup.py`. With that the Issue counts as resolved.
