### ISSUE TITLE
refactore creating record

### ISSUE THREAD

**Issue by utnapischtim** [fair-data-austria/invenio-rdm-pure#6]
use internal API aka invenio_records.api.Record

It should be checked where the permission handling comes in

- [x] create a record
- [ ] apply permissions works out of the box
- [ ] could be used over celery or in a cronjob
- [x] write a class to encapsulate the communication between the module and the database (after loading the content from the pure api, this class should be used to create/update/delete the record in the database)
- [ ] handle the file the same way as the metadata with internal API
- [ ] could be used with a not yet implemented sibling datamodel

**Comment by mb-wali** [comment]
Creating a record - 
As I was told the previous ```dev``` was using the invenioRDM data model based class to create a record for ```pure```, BUT to be sure @bengaal could you please add a ```permalink``` to where the current creating a record is taking place. to see what class is being used. Thanks

**Comment by bengaal** [comment]
> Creating a record -
> As I was told the previous `dev` was using the invenioRDM data model based class to create a record for `pure`, BUT to be sure @bengaal could you please add a `permalink` to where the current creating a record is taking place. to see what class is being used. Thanks

Data for the record is being prepared starting [here](https://github.com/tu-graz-library/invenio-rdm-pure/blob/9278fce27cc72b4af4d9353b3b6ef80ad7feb71a/invenio_rdm_pure/source/rdm/add_record.py#L75) and then it is POSTed [here](https://github.com/tu-graz-library/invenio-rdm-pure/blob/9278fce27cc72b4af4d9353b3b6ef80ad7feb71a/invenio_rdm_pure/source/rdm/add_record.py#L436).

**Comment by bengaal** [comment]
handle the file the same way as the metadata with internal API - 
I don't think this will work until Invenio sorts it out. As of now it says the functionality is temporarily disabled until the new API is completely compatible with it.
